name: Docs

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        working-directory: Mixd
        run: flutter pub get

      - name: Generate API docs
        working-directory: Mixd
        run: dart doc .

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # This points to the folder created by dart doc
          path: Mixd/doc/api/

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
